version: "3.9"
services:
  analyse:
    build: services/analyse/
    volumes:
      - ./services/analyse:/analyse
    ports:
      - "3000:3000"
  extract:
    build: services/extract/
    volumes:
      - ./services/extract:/extract
    ports:
      - "3001:3000"
  search:
    build: services/search/
    volumes:
      - ./services/search:/search
    ports:
      - "3002:3000"
  reply:
    build: services/reply/
    volumes:
      - ./services/reply:/reply
    ports:
      - "3003:3000"